### ISSUE TITLE
Update BTR release scripts to look at catalog-info.yaml for release info.

### ISSUE THREAD

**Issue by feanil** [openedx/repo-tools#439]
The [tag_release.py script](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/release/tag_release.py) in repo-tools currently looks at the `openedx.yaml` file to determine if a repo should be tagged for an open-edx release.  But we want to move this information into the `catalog-info.yaml` file.

Currently it looks for the `openedx-release` key in an openedx.yaml.  eg.
```yaml
openedx-release:
  ref: main
```

We want it to check to see if there is a `catalog-info.yaml` file and if it has an annotation for the openedx-release.  eg.

```yaml
metadata:
  annotations:
    openedx.org/release: "main"
```

## Tasks

- [x] Update the [tag_release.py script](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/release/tag_release.py) to read from both locations and prefer the info in catalog-info.yaml if it exists.
- [x] Get it reviewed by `nedbat` (You can still tag @feanil or other Aximprovements members for review first.)

**Comment by salman2013** [comment]
@feanil 
For the `openedx.yaml` file there is an addition [method](https://github.com/openedx/repo-tools/blob/c534010aae26cad7340f6eb0a2b29e2df5b76b21/edx_repo_tools/release/tag_release.py#L124) which check for parent repo and add some more information. is there a similar case that exists for the `catalog-info.yaml `file? 
if yes then i would also need to update this as the format for the catalog-info.yaml file is different and it is checking 
`openedx-release `tag.

```
def trim_dependent_repos(repos):
    """Remove dependent repos (an obsolete feature of this program).

    Repos with 'parent-repo' in their 'openedx-release' data are removed from
    the `repos` dict.  A new dict of repos is returned.

    """
    trimmed = {}

    for r, data in repos.items():
        if 'parent-repo' in data['openedx-release']:
            msg = f"Repo {r} is dependent: you can remove openedx-release from its openedx.yaml file"
            click.secho(msg, fg='yellow')
        else:
            trimmed[r] = data

    return trimmed
```

**Comment by feanil** [comment]
You can ignore this function, it should probably get removed.  See the first line of the docstring.  This feature is obsolete and we don't need to port it as a part of your changes.

**Comment by salman2013** [comment]
PR link https://github.com/openedx/repo-tools/pull/467
